server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  instance:
    preferIpAddress: true
  server:
    enableSelfPreservation: true
  client:
    registerWithEureka: true
    fetchRegistry: false

logging.level.com.netflix:
  eureka: OFF
  discovery: OFF